### ISSUE TITLE
Stoping CronJob

### ISSUE THREAD

**Issue by Himkar** [kelektiv/node-cron#301]
Have some question related to stop process of cronjob.
So I have a big pool of cronjobs which are scheduled in different time schedule. now suppose I have one job which runs in every 30 minute and took 20 minute to finish its job.
- It started running 10.00 AM 
- If I call stop() function at 10.10 AM, will it execute complete process or will interrupt it immediately ?
- After stop() call, will it again runs it on next interval?

Please help me to understand this. Thanks

**Comment by kevinkhill** [comment]
From what I can tell, the CronJob is like a light switch, so `.stop()` turns the light off and it will not run again unless you turn the light back on `.start()`

**Comment by yanickrochon** [comment]
Because JavaScript is single-threaded, and unless your job is running asynchronously, calling `stop` will always happen before or after the job actually executed. If your job is asynchronous, calling `stop` will not interrupt the job's execution if it is running; if is your responsibility to define this mechanism.
