### ISSUE TITLE
Running node-cron on forever

### ISSUE THREAD

**Issue by chadwtkns** [kelektiv/node-cron#313]
Hi all I'm trying to use forever to have my node app run in the background but the cron job doesn't seem to be running. Am I doing something wrong here?

Here is a snippet of what I'm doing inside my app.js

```
try {
	var job = new CronJob({
		cronTime:'0 */15 * * * 1-6',
		onTick: payload(url),
		start: false,
		onComplete: cronJobEnded()
	});
} catch(ex) {
    console.log('cron pattern not valid', ex);
}
job.start();

function cronJobEnded() {
	console.log('The cronJob has Ended');
}
```
and then I start the server up saying `forever start app.js` I get the onComplete message up front and then the job doesnt run every 15 minutes like I would expect. Any help is really appreciated.

**Comment by kevinkhill** [comment]
I am not certain, because I am a javascript novice.... but I believe it is not working because there is nothing in your script to keep it from ending. I had a similiar issue, but I think when you run `forever start app.js` it is similiar to just running `node app.js` so your job is setup, then it is started, and that's the end of the script.

I had tried to use `pm2` and I could see in the logs that my script just started, ended and restarted over and over. I suppose you could wrap it all in a `setInterval` of 500ms or do what I did, and add a simple `express` server on top, with buttons to start/stop the job. This was express is keeping the process alive, and in turn, keeping the cron job alive.

¯\_(ツ)_/¯ Seems to be working so far...

**Comment by yanickrochon** [comment]
The problem seem to be this line : `onTick: payload(url),` you set the `onTick` to whatever result the function `payload` returns. And I assume that the return of `payload` is undefined. Unless your `payload` function looks like this :

```
function payload(url) {
  return function () {
    // run your payload function
  };
}
```

**Comment by ncb000gt** [comment]
@chadwtkns I agree with what @yanickrochon suggested. If this is still an issue we can reopen this ticket.
