### ISSUE TITLE
Running Every 4th minute on offset

### ISSUE THREAD

**Issue by TimCody** [kelektiv/node-cron#321]
Is there a way to run a script every 4 minute, but on the 5 minute marks?

So instead of 0 0-55/5 * * * *

Running at 9:05, 9:10, 9:15, 9:20

I would want to run the script at

9:04, 9:09, 9:14, 9:19, etc....

I would expect to be able to do something such as 0 0-55/5+4 or something.  

My knowledge of cron syntax isn't that great, is there a way to do what I'm describing?

**Comment by ncb000gt** [comment]
You could do this using `0 4,9,14,19... * * * *`, but I'm not sure you'd be able to otherwise.

The cron syntax isn't terribly expressive. I've been considering, for a long time, reworking the parser or including a different parse, to allow for more expressiveness. It would need to be backwards compatible and pass the tests I have setup now. None that I've tried in the past have though and the parser rewrite took much longer than I anticipated and I ran out of time on it.
