### ISSUE TITLE
How to test a cron job

### ISSUE THREAD

**Issue by dongtanhuy** [kelektiv/node-cron#346]
I have a task to send Emai at 23h59 every day by calling `sendDailyEmail()` function, how can I write a test to make sure my code work correctly? I try to stub the `sendDailyEmail()` function, but when I run the test, the stubbed function is not called.
PS: I use Jest to write unit test.

**Comment by ncb000gt** [comment]
Well, you can probably grab some inspiration from the cron test suite. We use sinon fake timers to take control of the clock and tick the clock along until you hit the time you want. You'll likely need to mock whatever tool you're using to send email so that you don't actually send the email. Then you'd want to assert that your expectations were met.

That's the approach that I'd take, fake timers and mocking the library that sends the email.

**Comment by PavelPolyakov** [comment]
`sinon` is working, how about doing it with jest timers? I've tried and failed :) If anybody knows the answer - here is the issue: https://github.com/facebook/jest/issues/9971 .
