### ISSUE TITLE
Cron in firebase functions

### ISSUE THREAD

**Issue by salime45** [kelektiv/node-cron#348]
I using this project in firebase, 

The code works fine but is executing one time by each function in firebase

    console.log("Start Cron")

    const job = new CronJob({
        cronTime: '00 40 * * * *',
        onTick: function () {
            console.log("new Backup")
            newBackup()
        },
        start: false,
        timeZone: 'Europe/Madrid'
    });
    job.start()

**Comment by ncb000gt** [comment]
Hi!

I'm not really sure what you mean by this: `is executing one time by each function in firebase`.

Can you elaborate a bit more to help me out? Thanks!

**Comment by rosariopfernandes** [comment]
Hello @salime45 ,

What happens when you deploy a cloud function is: an instance of a container is created for each function and the resources are then duplicated to be used on both containers, as Doug explains in [this video](https://www.youtube.com/watch?v=rCpKxpIMg6o). That's why you see 1 execution per function.

Unfortunately, I don't think it's possible to use this library with Cloud Functions. Not only because of the duplicated resources, but also because the functions have timeouts, which will immediately stop the execution of your cron job.

If you want to create a Cron Job on Cloud Functions, I'd recommend trying the method described on the [Firebase Blog](https://firebase.googleblog.com/2017/03/how-to-schedule-cron-jobs-with-cloud.html)

**Comment by priyankinfinnov** [comment]
ICYMI: recently this was solved, read https://firebase.googleblog.com/2019/04/schedule-cloud-functions-firebase-cron.html
