### ISSUE TITLE
Periodic job is not working.

### ISSUE THREAD

**Issue by pawanDangi** [kelektiv/node-cron#354]
Hi Team,
I've used this pacage and have passed time string "59 59 03 * * *". So, it is run on every days at 5:30 AM (America Los Angeles time), but for some days it's not working and mostly they are Sunday & Monday.

here is the my code - 

```
import {CronJob} from 'cron';

const updateSelfStorageFacilityJob = new CronJob({
  cronTime: '59 59 03 * * *', 
  onTick: Meteor.bindEnvironment(function() {
    console.log('<==============start periodic job update self storage facility===============>')
  }),
  onComplete: function () {
    console.log('<=====complete periodic job update self storage facility=====>');
  },
  start: false,
  timeZone: 'America/Los_Angeles'
});

updateSelfStorageFacilityJob.start();
```

Would you please suggest me the steps for resolving it.

Thanks.

**Comment by ncb000gt** [comment]
That shouldn't run every day at 5:30, that should run every day at 4am depending on the date and time of the machine and the time from where you're viewing it.

The timezone should just make it run at that time.

I wrote a test for it because I was curious and it _appears_ to be working.

	it('should run every day', function() {
		var c = 0;
		var d = new Date('12/31/2014');
		d.setSeconds(59);
		d.setMinutes(59);
		d.setHours(23);
		var clock = sinon.useFakeTimers(d.getTime());

		var job = new cron.CronJob({
			cronTime: '59 59 3 * * *',
			onTick: function() {
				c++;
			},
			start: true,
			timeZone: 'America/Los_Angeles'
		});

		var twoWeeks = 14 * 24 * 60 * 60 * 1000;
		clock.tick(twoWeeks);

		clock.restore();
		job.stop();
		expect(c).to.eql(14);
	});

Is it possible that the Meteor binding is causing an issue or possibly whatever other mechanism is going on?
