### ISSUE TITLE
Firebase Cloud Functions - Long cronTime 

### ISSUE THREAD

**Issue by yuricamara** [kelektiv/node-cron#411]
Hi,

I am using this library with Firebase Cloud Functions. When I set the cronTime to some hours, the job doesn't run. When the cronTime is shorten, it works great.

Thanks!

**Comment by ncb000gt** [comment]
@yuricamara I'd would guess that's because if cloud functions are anything like AWS Lambdas they are capped at a runtime. If you're looking for something longer running then you'll want a dedicated machine/vm like EC2 or the GCP equiv.

Lambdas and cloud functions are intended to run over short time frames (less than 10 minutes) afaik. So, if they kill the function or time it out because it's hitting their limit then you wouldn't be able to run the cron over hours, only minutes.

Does that help?

**Comment by yuricamara** [comment]
Hi @ncb000gt , it makes a lot of sense.
Helped, of course.
Thank you!
