### ISSUE TITLE
what would happen if cron time is greater than MAX_DELAY??

### ISSUE THREAD

**Issue by harshsaini33483** [kelektiv/node-cron#424]
I was going to use node-cron in production code to execute a function every 15 of the month but I saw a MAX_DELAY variable which tell not to schedule a job greater than 24 days so why in example (time_dom_syntax_with_tz) they schedule a job greater than 24 days

**Comment by ncb000gt** [comment]
If you specify a job to run on the 15th of every month, it should do just that.

The MAXDELAY is in there because of the max number of MS a timeout in JS will _wait_. There is code in here after that which checks to see if the job should trigger, and if not, it will reset the timeout.

Does that help?

**Comment by harshsaini33483** [comment]
Yes that helps a lot
