### ISSUE TITLE
Passing context info in onTick function

### ISSUE THREAD

**Issue by ibansal** [kelektiv/node-cron#47]
We need to pass context info in onTick function the way this is implemented in setInterval, any support for this.

**Comment by Danielv3** [comment]
Hello. My code is using 1.3.0 version and I'm not able to send a custom context to the onTick function. If I don't send any context, the this.stop() method cannot be called neither because stop is not a function... Any ideas? thnks.

**Comment by ncb000gt** [comment]
@Danielv3 do you have a code sample you're using?

**Comment by Danielv3** [comment]
I solved the issue. You need to use "**function() {}**" instead of the newly arrow functions "**() => {}**" in order to be able to use "this" as context. In the newer arrow format you don't receive the context in **this**.

**Comment by charliecode** [comment]
I also had a similar issue as @Danielv3 while using a fat arrow function within a class on the onTick method. Because fat arrow functions get their "this" value from their enclosing lexical context and not the actual context they are within you don't actually get the cronJob attached to the "this" keyword inside the onTick function. Only a suggestion, but with more and more people using arrow functions by default it might be a good idea to add something to the docs about this. Arrow functions should not be used for the onTick method, only regular javascript functions.

**Comment by ncb000gt** [comment]
@charliecode I added a note, thanks for the suggestion.

**Comment by NonPolynomial** [comment]
Is there any plans to support arrow functions or are there any particular reasons against them?
It should be easy to pass the `this` context as a parameter to arrow functions.
E.g.
```js
onTick(this)
```

**Comment by ncb000gt** [comment]
I'd review a pr for this if you're interested and able, but at the moment
I'm too busy with other work to focus on it.

**Comment by NonPolynomial** [comment]
I'll have a look into it.

**Comment by NonPolynomial** [comment]
@ncb000gt currently there is the `onComplete` function that is passed to the `onTick` function.
Should that stay unchanged?
Users could instead call either `this.onComplete()` or - after my change - `job.onComplete()` to execute the that function.

[Context](https://github.com/kelektiv/node-cron/blob/master/lib/cron.js#L554)

**Comment by Kapsonfire-DE** [comment]
its more easy to use .apply or .call and pass the correct this param
