### ISSUE TITLE
Create cron jobs on every signup request

### ISSUE THREAD

**Issue by brunoqs** [kelektiv/node-cron#496]
I need to send email after 1, 3 and 5 days when the user register. If i create 3 jobs on every user signup request, can this slow the node down?

**Comment by ncb000gt** [comment]
Depends on the number of users you have. :)

Honestly to me, it seems like a better approach is to have 3 daily jobs that scan the database (maybe add some "sharding" if the DB is large), and sends and email to the users with those parameters.

For instance, daily job 1 would check for only those users whose created date was 1 day ago. This one then iterates through the list and sends email to each of them.

Then do the same thing but change the 1 day req to 3 and 5 days and you should be good. 3 jobs instead of 3 jobs for every user. 

Hope that helps.

**Comment by brunoqs** [comment]
I’ve tried this solution, but I did not have a good accuracy in the time of sending emails. If user signup today 10p.m, he needs to receive emails at 05/05 - 10p.m, 05/07 - 10.pm, and 05/09 - 10p.m.

**Comment by ncb000gt** [comment]
In that case I'd make them jobs that run every minute with the same parameters for the database queries. In that case you get up to the minute granularity and still get only 3 jobs. At some point your user list may outgrow this and the best option would be to start and have the jobs per shard, but I'm not sure of that first your needs right now.

**Comment by brunoqs** [comment]
@ncb000gt  I ll try to run one job every minute to check that, i think its better because i wont need to save jobs to run again if server goes down. Thx for the quick tips!

**Comment by ncb000gt** [comment]
Np. Gl!
