### ISSUE TITLE
Error: Something went wrong. cron reached maximum iterations.

### ISSUE THREAD

**Issue by iskoch01** [kelektiv/node-cron#500]
29 May 18:01:02 - [red] Uncaught Exception:
29 May 18:01:06 - Error: Something went wrong. cron reached maximum iterations.
						Please open an  issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string
						Time Zone: "" - Cron String: 0 0 18 * * * - UTC offset: -05:00 - current Date: Fri May 29 2020 18:00:57 GMT-0500
    at CronTime._getNextDateFrom (/usr/lib/node_modules/node-red/node_modules/cron/lib/cron.js:235:12)
    at CronTime.sendAt (/usr/lib/node_modules/node-red/node_modules/cron/lib/cron.js:156:17)
    at CronTime.getTimeout (/usr/lib/node_modules/node-red/node_modules/cron/lib/cron.js:175:29)

I am using Node-Red on a Giantboard (120 MB RAM).

**Comment by ncb000gt** [comment]
This happens when it takes longer than 5 seconds to find the next "start time" for the cron job. There is a pr up to show a "soft warning". But, this will only be a partial solution as the original code fixed an infinite loop issue. You can check out the pr https://github.com/kelektiv/node-cron/pull/499 for more detail.

Hopefully in the near future I'll be able to get a better solution in place.

**Comment by iskoch01** [comment]
Thanks. I’m running on a Giantboard, 128 MB. Seems I have a memory leak, and swapd kicks in, stalling the system. Some tweaks have help marginally, but finding the leak is turning out to be a challenge.

**Comment by lautaroramos** [comment]
#478

**Comment by iskoch01** [comment]
Duplicate
