### ISSUE TITLE
for month, 0-11 or 1-12? which one is right?

### ISSUE THREAD

**Issue by phymo** [kelektiv/node-cron#506]
![image](https://user-images.githubusercontent.com/7558104/85106804-66774e00-b23f-11ea-89cc-198148e8ef0e.png)
for month, 0-11 or 1-12? which one is right?

**Comment by phymo** [comment]
why most docments shows 1-12? Is there anything wrong?

**Comment by climba03003** [comment]
It should be 0-11 in this lib. You can find the reason in the [source code](https://github.com/kelektiv/node-cron/blob/master/lib/time.js#L25-L36).

Moreover, the document you found is about crontab which is the linux system cron file specification.

**Comment by phymo** [comment]
Thank you for replying. I'm just confused why this repo do not keep consistant with other documents~

**Comment by ktersius** [comment]
This is quite a gotcha. Even the https://crontab.guru/ link that this project refers to uses 1-12 for the months.

**Comment by fabripeco** [comment]
Same (1-12) at https://crontab.cronhub.io/ . Which is the correct CRON standard? [Linux Man pages](https://linux.die.net/man/5/crontab) seems to indicate 1-12. Why does the library use the 0-11 standard?
Thank you

**Comment by ncb000gt** [comment]
The cron ranges are all listed in the readme: months are 0-11

https://github.com/kelektiv/node-cron#cron-ranges

In short, this project started from another and some of those early decisions carried over. It hasn't been changed due to backwards compatibility concerns. I don't have a lot of time to upkeep this project (see the other issues in this project that have lagged for a while) and so I haven't been able to change this kind of thing while taking the backwards compatibility concerns into account.
