### ISSUE TITLE
Not working '* */15 * * * *'

### ISSUE THREAD

**Issue by igordeoliveirasa** [kelektiv/node-cron#535]
Steps are working only */1 and */2. When I use */3 and so on it does not work..

**Comment by P4sca1** [comment]
Hey @igordeoliveirasa 👋
You might want to give https://github.com/P4sca1/cron-schedule a try.

**Comment by Shogobg** [comment]
@igordeoliveirasa works fine for me.
This package is a bit tricky because it also has configuration for seconds.

If we take the configurations that you mentioned, your task will run like this:
'* */1 * * * *' - This is the same as '* * * * * *', runs every second of every minute - 3600 times in an hour
'* */2 * * * *' - This will run on every second, on every two minutes - 1800 times in an hour
...
'* */15 * * * *' - Will run on every second, on every 15 minutes - 240(at 00, 15, 30, 45 minutes) times in an hour

If you want it to run once every X minutes, you need to do this:
'00 */X * * * *'

Can you describe your issue?

**Comment by PaddyOl** [comment]
@Shogobg : that means https://github.com/kelektiv/node-cron/blob/master/examples/at_10_minutes.js is wrong ... sonce it's not at 10, but every seconds at 10 ...

**Comment by Shogobg** [comment]
> @Shogobg : that means https://github.com/kelektiv/node-cron/blob/master/examples/at_10_minutes.js is wrong ... since it's not at 10, but every seconds at 10 ...
> 
> 

Yeah, it looks like it's named incorrectly.

**Comment by intcreator** [comment]
the behavior has since been updated so it matches Linux cron more closely. if you leave out the seconds the seconds will default to `0` instead of `*`. the example linked has also been fixed. going to close this as completed
