### ISSUE TITLE
error: bundling failed: Error: Unable to resolve module `child_process`

### ISSUE THREAD

**Issue by maihonganh1997** [kelektiv/node-cron#538]
I installed cron package then it gives an error like this: "error: bundling failed: Error: Unable to resolve module `child_process` from `project/node_modules/cron/lib/cron.js`: Module `child_process` does not exist in the Haste module map"
react-native: 0.59.9
cron: 1.8.2
how to fix it? please

**Comment by danielehrhardt** [comment]
Same Issue here.

**Comment by sheerlox** [comment]
Hi, unfortunately, we currently do not support running in the browser.

We discussed removing `child_process`, which is used to run system commands from `cron` by providing a string instead of a function (IIRC).

There's [an old PR](https://github.com/kelektiv/node-cron/pull/629) related to this issue, but it is outdated. 

We would gladly accept a similar PR that would disable the system commands feature in the browser environment.
