### ISSUE TITLE
Cron job got executed twice on Azure Web App

### ISSUE THREAD

**Issue by brechtarnou** [kelektiv/node-cron#543]
Hi all,

My cron job gets executed twice on my azure web app. 

![image](https://user-images.githubusercontent.com/58935002/101390304-e57e4280-38c2-11eb-8213-052024238f51.png)

Even a simple console.log('hi'), gets executed twice. 
Anyone knows what this could be?

Kind regards,
Brecht

**Comment by davidlane-iteratec** [comment]
Maybe you have 2 instances?

**Comment by NareshKukreti12** [comment]
Have you resolved this issue @brechtarnou . I am also facing the same issue on AWS.

**Comment by NareshKukreti12** [comment]
> Maybe you have 2 instances?

I am also facing the same. On local server this is working perfectly, but after deploying on AWS the cron triggering twice . I have multiple crons running in the project and each cron is running twice. DON'T know how to resolve this

**Comment by mandyGitH** [comment]
@NareshKukreti12 @brechtarnou not sure if you are still facing this issue. I recently ran into this after deploying app to Azure web and resolved the problem by fixing the number of instances - inspired by @davidlane-iteratec's comment. In my case, turned out that the app had been set to default to 5 instances constantly. Reducing to one instance stopped the issue immediately.

Alternatively, if you prefer to keep >1 instance for performance optimization, try leveraging autoscale to dynamically control the number of instances - this has effectively resolved the issue for me

Might be something similar on AWS? @NareshKukreti12

**Comment by intcreator** [comment]
if it's working fine on a local server and not on a deployed environment that should be an issue with environment configuration unrelated to node-cron

**Comment by petetnt** [comment]
FWIW, we have a similar issue in Google Cloud Run, the `node-cron` tasks are ran multiple times (3 to be exact), while they are working locally. There's multiple issues about it, such as this, https://github.com/kelektiv/node-cron/issues/349, https://github.com/kelektiv/node-cron/issues/305 and with libraries that use `node-cron` as dependency such as https://github.com/nestjs/schedule/issues/454 and https://github.com/nestjs/schedule/issues/445 etc. that all show similar symptoms with different descriptions so I am pretty sure that the issue is on `node-cron`s end

**Comment by sheerlox** [comment]
See also:
- https://github.com/kelektiv/node-cron/issues/489
