### ISSUE TITLE
Can CronJob instance be garbage collected?

### ISSUE THREAD

**Issue by alex-uw** [kelektiv/node-cron#577]
I have a long running backend server process (can be running for days and weeks)

In one file I have this function which initialises cron job

```js
export function cronInit() {
    const job: CronJob = new CronJob('* * * * * *', async () => {
        // some code here
    });

    job.start();
}
```

from another place I call cronInit() once on server startup

After some time after server started (few days) - cron stops working - is this because instance of CronJob is a local variable and it's getting cleared by GC?

**Comment by intcreator** [comment]
how can you tell that cron stops working? are you sure your script or something else hasn't stopped working? I use node-cron for Discord bots that run for months at a time and I haven't had this issue

I doubt this is caused by garbage collection...the only way that would happen is if you somehow reassigned `cronInit` so another value so its contents were unreachable by the global root

going to close this as cannot reproduce for now. feel free to reopen if you have more details
