### ISSUE TITLE
What is the point of using node-cron instead of using crontab ?

### ISSUE THREAD

**Issue by qiulang** [kelektiv/node-cron#637]
Sorry if this question has been asked but I search the issues and I can't find one.

So if I can just use crontab why should I  use node-cron then? What are the function node-cron provides crontab doesn't ?
I also assume I need a process manager like pm2 to keep my script running in order to make my cron job work. That only adds to my doubt that isn't just using crontab much easier ?

Maybe this can be seen as a document request to explain the doubts I have here.

Thanks.

**Comment by blascokoa** [comment]
crontab and node-cron got different purposes.

- `crontab` can execute scripts at certain time, but cannot interact with already running scripts
- `node-cron` can be executed in the interaction of another script for different purposes, lets say you got a bot running, and each certain time, you want to send a message, you will use node-cron for that purpose because you cannot run 2 instances of your bot at same time without issues.

**Comment by qiulang** [comment]
Thanks for answering my question. So I assume I need a process manager like pm2 to keep my script running in order to make my node-cron job work.  Is that right ?

**Comment by blascokoa** [comment]
Depends of how it's coded your script, but yeah, deploy pm2 if you want to keep it running it's always a good option

**Comment by qiulang** [comment]
Can you elaborate that "Depends of how it's coded your script" ? 

To me I feel it is a **must**, e.g. if I schedule my  node-cron job to run at, say 1 am, without pm2 (or any process manager for that matter) how can I make sure my script is still alive at 1 am ?

**Comment by blascokoa** [comment]
infinite loop and a proper error handling system

**Comment by intcreator** [comment]
I feel like this question has been answered adequately to close the issue. if you want to discuss cron implementations more, feel free to do so on the [Discord server](https://discord.gg/yyKns29zch)
