### ISSUE TITLE
JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by cyar2** [kelektiv/node-cron#874]
Cron reached maximum iterations

TimeZone: "" -Cron String: 009*** -UTC offset: +10:00 - current Date: Sat Apr 06 2024 08:17:14 GMT+1000
at CronTime._getNextDateFrom (C:\Program
Files\Fing\resources\app.asar\node_modules\cron\lib\cron.js.235:12)
at CronTime.sendAt (C:\Program
Files

etc etc

![image](https://github.com/kelektiv/node-cron/assets/166180513/e284c339-64e0-447c-b411-6e0664168d34)

**Comment by sheerlox** [comment]
This bug [was fixed](https://github.com/kelektiv/node-cron/commit/c685c63a6d7fa86d6c8afca29b536b9da24e824b) in v2.4.1.

It looks like you're encountering this error while using some software, so the best way to resolve that issue is to contact the software developers and point them to this issue so they can take the appropriate steps (upgrading to at least v2.4.1 will fix the issue, but taking the time to upgrade to v3 would also be a good investment to make sure future bug fixes can be received easily).
