### ISSUE TITLE
Javascript error occurred in the main process

### ISSUE THREAD

**Issue by wlkoerner** [kelektiv/node-cron#875]
![cron_error_in_fing](https://github.com/kelektiv/node-cron/assets/128849589/017b7d5d-6e93-480a-b7a3-2f9b327cd47b)

**Comment by sheerlox** [comment]
This bug [was fixed](https://github.com/kelektiv/node-cron/commit/c685c63a6d7fa86d6c8afca29b536b9da24e824b) in v2.4.1.

It looks like you're encountering this error while using some software, so the best way to resolve that issue is to contact the software developers and point them to this issue so they can take the appropriate steps (upgrading to at least v2.4.1 will fix the issue, but taking the time to upgrade to v3 would also be a good investment to make sure future bug fixes can be received easily).
