### ISSUE TITLE
Unraid api crash

### ISSUE THREAD

**Issue by bear0328** [kelektiv/node-cron#885]
May 17 00:35:10 Tower unraid-api[9110]: ⚠️ Caught exception: Something went wrong. cron reached maximum iterations.#012#011#011#011#011#011#011Please open an issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string#012#011#011#011#011#011#011Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +08:00 - current Date: Fri May 17 2024 00:35:06 GMT+0800

**Comment by sheerlox** [comment]
This bug [was fixed](https://github.com/kelektiv/node-cron/commit/c685c63a6d7fa86d6c8afca29b536b9da24e824b) in v2.4.1.

It looks like you're encountering this error while using some software, so the best way to resolve that issue is to contact the software developers and point them to this issue so they can take the appropriate steps (upgrading to at least v2.4.1 will fix the issue, but taking the time to upgrade to v3 would also be a good investment to make sure future bug fixes can be received easily).
