### ISSUE TITLE
 Caught exception: Something went wrong. cron reached maximum 4th time in 2 weeks

### ISSUE THREAD

**Issue by mdonkersloot73** [kelektiv/node-cron#921]
Hi

I was asked to report this problem, first thought is was "again" my usb stick.
but this might not be the case

Nov 20 02:28:30 Tower unraid-api[8529]: ⚠️ Caught exception: Something went wrong. cron reached maximum iterations.#012#011#011#011#011#011#011Please open an issue (https://github.com/kelektiv/node-cron/issues/new) and provide the following string#012#011#011#011#011#011#011Time Zone: "" - Cron String: 0 * * * * * - UTC offset: +01:00 - current Date: Wed Nov 20 2024 02:28:30 GMT+0100
Nov 20 02:28:31 Tower unraid-api[8529]: ⚠️ UNRAID API crashed with exit code 1
Nov 20 02:30:27 Tower flash_backup: adding task: /usr/local/emhttp/plugins/dynamix.my.servers/scripts/UpdateFlashBackup update

Regards Marco

**Comment by sheerlox** [comment]
Hi, this bug [was fixed](https://github.com/kelektiv/node-cron/commit/c685c63a6d7fa86d6c8afca29b536b9da24e824b) in v2.4.1.

It looks like you're encountering this error while using some software, so the best way to resolve that issue is to contact the software developers and point them to this issue so they can take the appropriate steps (upgrading to at least v2.4.1 will fix the issue, but taking the time to upgrade to v3 would also be a good investment to make sure future bug fixes can be received easily).
