### ISSUE TITLE
Not able to run cron on local timezone

### ISSUE THREAD

**Issue by buzzshiva** [kelektiv/node-cron#98]
I have set my ubuntu to Asia/Kolkata, and i'm trying to run the below job. Its not running. Am i missing something here.

Also note ; I have installed npm install time.

var job = new CronJob('00 18 9 \* \* 1-5', function(){
    // Runs every weekday (Monday through Friday)
    // at 9:18:00 AM. It does not run on Saturday
    // or Sunday.
    console.log('Job Started');
  }, function () {
    // This function is executed when the job stops
    console.log("Job Ended");
  },
  true /\* Start the job right now _/,
  "Asia/Kolkata" //timeZone /_ Time zone of this job. */
);

**Comment by reggi** [comment]
I don't understand this message

> You specified a Timezone but have not included the `time` module. Timezone functionality is disabled. Please install the `time` module to use Timezones in your application.

Why isn't `time` included as a dependency?

**Comment by ncb000gt** [comment]
The time module was a dependency but isn't in master (possibly the latest
version of the module, I can't remember off the top of my head).

The time module was a separate module that wasn't strictly necessary for
the cron module to run so it was available as an option, for people to
specify timezones, plus it was a c/c++ addon which caused issues when
trying to use it in windows. I've since moved over to moment-timezone and,
IIRC, do include this as a dependency because it works on all platforms.

Take a look at master to give it a try.

- Nick Campbell
